import Link from 'next/link';
import { DiscoveryShell, PageSchema } from '@/components/discovery';
import { cityPath, data, formatDate } from '@/lib/organic';
import {pageMetadata} from '@/lib/metadata';
export const metadata=pageMetadata('/levantamento','Levantamento: cinco recortes urbanos no snapshot Obrasgov','Comparação reproduzível de registros associados à geometria de cinco cidades no snapshot do Radar de Obras.');
export default function Survey(){
  const stats=data.cities.map(city=>({city,total:city.rows.length,execution:city.rows.filter(row=>row.status==='Em execução').length,withValue:city.rows.filter(row=>typeof row.investmentTotal==='number'&&row.investmentTotal>0).length}));
  const total=stats.reduce((sum,row)=>sum+row.total,0);
  return <DiscoveryShell crumbs={[{name:'Início',path:'/'},{name:'Levantamento',path:'/levantamento'}]}>
    <PageSchema path="/levantamento" name="Levantamento de cinco recortes urbanos" description="Contagem reproduzível de registros do snapshot Obrasgov associados a cinco municípios pela geometria da fonte." />
    <div className="eyebrow">Levantamento do Radar · {formatDate(data.source.collectedAt)}</div><h1>Cinco cidades, {total.toLocaleString('pt-BR')} registros associados</h1><p className="lead">Somando apenas os registros com o município e a UF exatos na geometria do snapshot, os cinco recortes piloto reúnem {total.toLocaleString('pt-BR')} IDs únicos. A comparação mostra a distribuição no cadastro consultado, não o volume real de obras ou investimentos de cada cidade.</p>
    <div className="table-scroll"><table className="work-table survey-table"><caption>Contagens derivadas do snapshot Obrasgov</caption><thead><tr><th>Cidade</th><th>Registros associados</th><th>Situação “Em execução”</th><th>Com investimento previsto positivo</th></tr></thead><tbody>{stats.map(item=><tr key={item.city.slug}><td><Link href={cityPath(item.city)}>{item.city.name}/{item.city.uf}</Link></td><td>{item.total.toLocaleString('pt-BR')}</td><td>{item.execution.toLocaleString('pt-BR')}</td><td>{item.withValue.toLocaleString('pt-BR')}</td></tr>)}</tbody><tfoot><tr><th scope="row">Total dos cinco recortes</th><td>{total.toLocaleString('pt-BR')}</td><td>{stats.reduce((n,item)=>n+item.execution,0).toLocaleString('pt-BR')}</td><td>{stats.reduce((n,item)=>n+item.withValue,0).toLocaleString('pt-BR')}</td></tr></tfoot></table></div>
    <section className="reading-section"><h2>Como reproduzir</h2><p>Leia os blocos listados em <Link href="/data/projects-manifest.json">projects-manifest.json</Link>, valide a contagem e os IDs únicos, e filtre por <code>city</code> e <code>uf</code> iguais aos pares acima. Conte <code>status === &quot;Em execução&quot;</code> e <code>investmentTotal &gt; 0</code> apenas dentro desse recorte. O gerador do repositório usa essa regra para as páginas.</p><p>A coleta dos projetos ocorreu em {formatDate(data.source.collectedAt)} e a complementação dos valores em {formatDate(data.source.investmentCollectedAt)}. O rótulo de cidade pode se referir a ponto aproximado ou administrativo; por isso os números não são ranking de atividade, eficiência ou execução local. <Link href="/metodologia">Leia as limitações completas.</Link></p></section>
    <p className="context-note">As <Link href="/obras">dez fichas do piloto</Link> mostram como examinar um registro individual e abrir sua fonte oficial.</p>
  </DiscoveryShell>;
}
