import Link from 'next/link';
import { DiscoveryShell, PageSchema } from '@/components/discovery';
import { API, SOURCE_PAGE, data, formatDate } from '@/lib/organic';
import {pageMetadata} from '@/lib/metadata';

export const metadata=pageMetadata('/metodologia','Metodologia e cobertura | Radar de Obras','Como o Radar de Obras usa o snapshot Obrasgov, associa municípios, valida IDs e interpreta situação, datas e investimentos previstos.');
export default function Methodology(){return <DiscoveryShell crumbs={[{name:'Início',path:'/'},{name:'Metodologia',path:'/metodologia'}]}>
  <PageSchema path="/metodologia" name="Metodologia e cobertura" description="Origem, período, critérios e limites dos dados publicados pelo Radar de Obras." />
  <div className="eyebrow">Transparência dos dados</div><h1>Metodologia e cobertura</h1><p className="lead">O Radar apresenta uma leitura independente de registros da API pública Obrasgov. O cadastro consultado não abrange necessariamente todas as obras do Brasil nem todas as obras de cada município.</p>
  <section className="reading-section"><h2>Fonte e recorte</h2><p>A fonte é a <a href={SOURCE_PAGE} target="_blank" rel="noopener noreferrer">API de Dados Abertos do Obrasgov.br ↗</a>, mantida pelo Ministério da Gestão e da Inovação em Serviços Públicos. O snapshot do mapa contém {data.source.sourceTotal.toLocaleString('pt-BR')} cadastros retornados pelo endpoint <code>projeto-investimento</code> na coleta de {formatDate(data.source.collectedAt)}. A fonte indicou carga de {formatDate(data.source.sourceLoad)}. Valores de investimento foram complementados em {formatDate(data.source.investmentCollectedAt)}.</p><p>As páginas de cidades exibem apenas registros cujo campo de município associado à geometria corresponde exatamente à cidade e à UF da página. Registros sem município, com múltiplos municípios ou com outro rótulo não entram nesse total. A localização não foi confirmada em campo.</p></section>
  <section className="reading-section"><h2>Identidade, validação e deduplicação</h2><p>O ID <code>id_projeto_investimento</code> é a chave das fichas. O gerador valida a contagem dos blocos do snapshot, a contagem total, IDs únicos e valores numéricos válidos antes de gerar as páginas. As dez fichas do piloto foram consultadas também pelo ID na API oficial. Município, UF e nome foram conferidos contra o snapshot antes de publicar detalhes complementares.</p><p>O hash SHA-256 do manifesto e dos blocos de entrada nesta versão é <code className="wrap-code">{data.sourceHash}</code>. Uma atualização só deve substituir os arquivos após validação; falha da fonte mantém o último snapshot válido e sua data real.</p></section>
  <section className="reading-section"><h2>O que os campos significam</h2><ul><li><strong>Situação:</strong> rótulo publicado pelo sistema, sem auditoria independente da execução.</li><li><strong>Datas previstas:</strong> planejamento informado, que pode ter sido revisto. Previsão vencida não comprova atraso.</li><li><strong>Datas efetivas:</strong> preenchimento da fonte na consulta complementar. Um campo vazio não equivale a zero, e divergências devem ser verificadas na fonte.</li><li><strong>Investimento previsto:</strong> valor informado como previsão de investimento. Não representa gasto, pagamento ou contratação. Valores ausentes ou sem valor positivo não entram em somas.</li><li><strong>Município e ponto:</strong> georreferência publicada. Pode indicar referência ou sede administrativa, não o canteiro.</li></ul></section>
  <section className="reading-section"><h2>Atualização e reutilização</h2><p>O mapa usa o snapshot local validado; as fichas mostram separadamente a data da consulta complementar. O site não cria histórico retroativo. Uma fotografia em uma data não mostra quando uma mudança ocorreu. O refresh do piloto é operado com o script do repositório e uma revisão semanal documentada; novas publicações só ocorrem após validar a fonte e os resultados.</p><p>Os arquivos do piloto em <Link href="/dados">Dados e downloads</Link> têm atribuição e dicionário de campos. A página da API oficial divulga o acesso público, mas não encontramos uma licença específica para os dados da API; o código MIT deste projeto não é licença dos dados da fonte. Consulte os termos oficiais antes de redistribuição ampliada.</p><p><Link href="/guia-de-interpretacao">Guia de interpretação →</Link> · <a href={`${API}/openapi.json`} target="_blank" rel="noopener noreferrer">Esquema da API ↗</a></p></section>
  <section className="reading-section" id="tipo-derivado"><h2>Tipo identificado no título</h2><p>Além da classificação oficial, algumas fichas mostram uma indicação do equipamento citado no nome cadastrado. Regras fixas reconhecem referências diretas a UBS, UPA, CAPS, creche/educação infantil, restaurante/refeitório e biblioteca. Exigimos o nome exato do equipamento ou uma expressão direta no início, como “construção de biblioteca”. Menções a uma rua, passarela ou outro local não bastam. Casos sem correspondência ficam sem indicação adicional.</p><p>A regra é recalculada a partir do título em cada renderização da ficha. Quando uma nova carga validada altera esse título, a indicação acompanha o novo texto automaticamente. O título original fica acessível ao lado da explicação. A área, o tipo e o subtipo publicados pelo órgão continuam preservados.</p><p>A versão inicial foi conferida em 120 correspondências, 20 por categoria, e 20 casos difíceis separados da revisão anterior por ID. As 120 correspondências foram consideradas compatíveis nessa revisão, feita por um agente, sem avaliação externa independente. Há repetição de títulos, principalmente em saúde, e perda de cobertura em outras formas de escrever. Isso não demonstra precisão garantida nem confirma o objeto no local, a entrega ou o funcionamento.</p><p>Uma reforma interna pode ser identificada pelo equipamento envolvido. A indicação não descreve necessariamente toda a intervenção e não serve, isoladamente, para comparar custos.</p></section>
</DiscoveryShell>}
