import {officialRecords} from '@/lib/official-records.mjs';
import {officialPageRecords} from '@/lib/official-page-cache.mjs';
import {Progress} from '@/components/ui/progress';
import {formatDate} from '@/lib/organic';
type Result=Awaited<ReturnType<typeof officialRecords>>;
const money=(x:unknown)=>typeof x==='number'&&Number.isFinite(x)?new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(x):'Não informado';
function documentUrl(value:unknown){try{if(typeof value!=='string')return null;const url=new URL(value);return url.protocol==='https:'&&!url.username&&!url.password?url.href:null;}catch{return null;}}
function Completeness({result,label}:{result:Result;label:string}){
 if(result.complete)return null;
 return <p className="context-note">{result.rows.length?`${label}: consulta parcial. Há registros adicionais ou indisponíveis.`:`${label}: a consulta está indisponível. Isso não significa ausência de registros.`}</p>;
}
export type PageRecords = {contracts:Result;executions:Result;commitments:Result;studies:Result;checkedAt:string};
export async function OfficialWorkRecords({id, records}:{id:string; records?:PageRecords}){
 const {contracts,executions,commitments,studies,checkedAt}=records ?? await officialPageRecords(id) as PageRecords;
 const percent=executions.complete&&executions.rows.length===1?executions.rows[0].percentual_execucao_fisica:null;
 const validPercent=typeof percent==='number'&&Number.isFinite(percent)&&percent>=0&&percent<=100;
 return <section className="enrichment-section" id="contratos-andamento"><h2>Contratos, andamento e recursos</h2>
  <p className="source-caption">Consulta complementar ao Obrasgov em {formatDate(checkedAt)}. Pode ser mais recente que o cadastro acima. Resultados completos podem ser reutilizados por até 6 horas.</p>
  <Completeness result={contracts} label="Contratos"/>
  {contracts.rows.length>0?<div className="official-contracts"><h3>{contracts.rows.length} contrato(s): empresas, valores e documentos{!contracts.complete?' — parcial':''}</h3><div className="record-grid">{contracts.rows.map((c,index)=>{const url=documentUrl(c.link_transparencia);return <article className="record-card" key={`${c.id_contrato}-${index}`}><h3>Contrato {c.numero_contrato||'sem número informado'}</h3><dl className="compact-list"><div><dt>Empresa contratada</dt><dd>{c.fornecedor_contrato||'Não informada'}</dd></div><div><dt>CNPJ da empresa</dt><dd>{c.cnpj_fornecedor_contrato||'Não informado'}</dd></div><div><dt>Valor global do contrato</dt><dd>{money(c.valor_global_contrato)}</dd></div><div><dt>Vigência informada</dt><dd>{formatDate(c.vigencia_inicio_contrato)} a {formatDate(c.vigencia_fim_contrato)}</dd></div><div><dt>Licitação</dt><dd>{c.licitacao_numero||'Não informada'}</dd></div><div><dt>Processo</dt><dd>{c.processo||'Não informado'}</dd></div></dl>{c.objeto_contrato&&<p>{c.objeto_contrato}</p>}{url&&<a href={url} target="_blank" rel="noopener noreferrer">Documento oficial do contrato ↗</a>}</article>;})}</div><p className="context-note">O objeto e a vigência definem o vínculo da empresa. Não afirmam atuação atual. Valor contratual e investimento previsto são medidas diferentes.</p></div>:contracts.complete&&<p>Nenhum contrato retornado nesta consulta. Isso não prova que não houve contratação.</p>}
  <section id="execucao-fisica" className="official-subsection"><h3>Andamento da obra</h3>
  {validPercent&&<div className="overview-progress"><div className="progress-heading"><h3>Execução física informada</h3><strong>{percent.toLocaleString('pt-BR')}%</strong></div><Progress value={percent} aria-label="Percentual de execução física informado" className="work-progress"/><p className="context-note">Atualização do registro: {formatDate(executions.rows[0].dt_atualizacao_execucao||executions.rows[0].dt_cadastro_execucao)}. O percentual não confirma entrega ou funcionamento.</p></div>}
  <Completeness result={executions} label="Andamento"/>
  {executions.rows.length>0?<div className="execution-records"><h4>{executions.rows.length} medição(ões) de execução física{!executions.complete?' — parcial':''}</h4>{executions.rows.map((e,index)=><dl className="detail-list" key={`${e.id_execucao_fisica}-${index}`}><div><dt>Execução física informada</dt><dd>{typeof e.percentual_execucao_fisica==='number'?`${e.percentual_execucao_fisica.toLocaleString('pt-BR')}%`:'Não informada'}</dd></div><div><dt>Atualização do registro</dt><dd>{formatDate(e.dt_atualizacao_execucao||e.dt_cadastro_execucao)}</dd></div><div><dt>Início registrado</dt><dd>{formatDate(e.dt_inicial_execucao)}</dd></div><div><dt>Fim registrado</dt><dd>{formatDate(e.dt_final_execucao)}</dd></div></dl>)}<p className="context-note">Medições podem se referir a instrumentos diferentes. Não foram somadas e não comprovam entrega ou funcionamento.</p></div>:executions.complete&&<p>Nenhuma medição retornada nesta consulta.</p>}
  </section><section id="empenhos" className="official-subsection"><h3>Empenhos e pagamentos</h3>
  <Completeness result={commitments} label="Empenhos"/>
  {commitments.rows.length>0?<div className="financial-records"><h4>{commitments.rows.length} empenho(s): valores e pagamentos por registro{!commitments.complete?' — parcial':''}</h4><div className="record-grid">{commitments.rows.map((c,index)=><article className="record-card" key={`${c.nr_empenho}-${index}`}><h3>Empenho {c.nr_empenho||'sem número informado'}</h3><dl className="compact-list"><div><dt>Credor</dt><dd>{c.credor||'Não informado'}</dd></div><div><dt>Valor do empenho</dt><dd>{money(c.valor_empenho)}</dd></div><div><dt>Pago informado</dt><dd>{money(c.pago)}</dd></div><div><dt>Restos a pagar pagos</dt><dd>{money(c.rppago)}</dd></div></dl></article>)}</div><p className="context-note">Valores por registro. Não foram somados: exercícios e situações podem se sobrepor. Empenho, pagamento, valor contratual e investimento previsto são medidas diferentes.</p></div>:commitments.complete&&<p>Nenhum empenho retornado nesta consulta. Isso não prova ausência de despesas.</p>}
  </section><section id="estudos" className="official-subsection"><h3>Estudos de viabilidade</h3>
  <Completeness result={studies} label="Estudos de viabilidade"/>
  {studies.rows.length>0?<div><h4>{studies.rows.length} registro(s) de estudo de viabilidade{!studies.complete?' — parcial':''}</h4><ul>{studies.rows.map((s,index)=><li key={index}><strong>{s.tipo_estudo_viabilidade||'Tipo não informado'}:</strong> {s.especificacao_estudo_viabilidade||'Sem especificação'}</li>)}</ul><p className="context-note">O registro não equivale a acesso ao documento integral nem comprova viabilidade.</p></div>:studies.complete&&<p>Nenhum estudo de viabilidade retornado nesta consulta.</p>}
 </section></section>;
}

