import Link from 'next/link';
import { DiscoveryShell, PageSchema, Structured } from '@/components/discovery';
import { ORIGIN, SOURCE_PAGE, data, formatDate } from '@/lib/organic';
import {pageMetadata} from '@/lib/metadata';
export const metadata=pageMetadata('/dados','Dados e downloads | Radar de Obras','Baixe CSV e JSON das dez fichas piloto, com dicionário de campos, fonte, período, cobertura e limitações.');
export default function DataPage(){return <DiscoveryShell crumbs={[{name:'Início',path:'/'},{name:'Dados',path:'/dados'}]}>
  <PageSchema path="/dados" name="Dados e downloads do piloto" description="Dez registros selecionados do snapshot Obrasgov, disponíveis em CSV e JSON com dicionário de campos." />
  <Structured data={{'@context':'https://schema.org','@type':'Dataset','@id':`${ORIGIN}/dados#dataset`,name:'Fichas piloto do Radar de Obras',description:'Dez projetos selecionados em cinco cidades com campos do snapshot Obrasgov e consulta complementar à API.',creator:{'@type':'Person',name:'Ricardo Guia',url:'https://ricardoguia.com'},url:`${ORIGIN}/dados`,isBasedOn:SOURCE_PAGE,spatialCoverage:{'@type':'Place',name:'Cinco cidades piloto no Brasil: Rio de Janeiro, São Paulo, Belo Horizonte, Salvador e Recife'},dateModified:data.source.investmentCollectedAt,distribution:[{'@type':'DataDownload',encodingFormat:'text/csv',contentUrl:`${ORIGIN}/dados/piloto-obras.csv`},{'@type':'DataDownload',encodingFormat:'application/json',contentUrl:`${ORIGIN}/dados/piloto-obras.json`}]}} />
  <div className="eyebrow">Dados abertos · Piloto</div><h1>Baixe os dados das dez fichas</h1><p className="lead">CSV e JSON contêm apenas os dez projetos publicados como fichas. Campos principais vêm do snapshot de {formatDate(data.source.collectedAt)}; descrições e datas efetivas foram consultadas posteriormente na API oficial.</p>
  <div className="download-grid"><a href="/dados/piloto-obras.csv" download data-analytics-action="exportar_dados"><strong>CSV</strong><span>Uma linha por ID · UTF-8 · separador vírgula</span><b>Baixar CSV ↗</b></a><a href="/dados/piloto-obras.json" download data-analytics-action="exportar_dados"><strong>JSON</strong><span>Objeto com metadados e lista de dez registros</span><b>Baixar JSON ↗</b></a></div>
  <section className="reading-section"><h2>Dicionário de campos</h2><div className="table-scroll"><table className="work-table dictionary"><thead><tr><th>Campo</th><th>Significado</th></tr></thead><tbody>{[
    ['id','Identificador estável id_projeto_investimento na API Obrasgov.'],['name','Nome informado pela fonte.'],['city, uf','Município e UF associados à geometria; não confirmam o canteiro.'],['status','Situação cadastrada no snapshot, sem verificação em campo.'],['organization','Organização responsável informada.'],['start, end','Datas previstas de início e fim, em ISO 8601.'],['actualStart, actualEnd','Datas efetivas informadas na consulta complementar; null significa ausência.'],['investmentTotal','Investimento previsto em reais (BRL); não é gasto ou pagamento.'],['point','Longitude e latitude informadas; podem ser aproximadas.'],['detailCheckedAt','Data da consulta complementar à API.'],['sourceUrl','Consulta oficial do ID no endpoint projeto-investimento.'],
  ].map(([field,meaning])=><tr key={field}><td><code>{field}</code></td><td>{meaning}</td></tr>)}</tbody></table></div></section>
  <section className="reading-section"><h2>Proveniência e limites</h2><p>Fonte: <a href={SOURCE_PAGE} target="_blank" rel="noopener noreferrer">API de Dados Abertos do Obrasgov.br ↗</a>. O snapshot reúne {data.source.sourceTotal.toLocaleString('pt-BR')} cadastros da coleta do mapa; este download publica somente as dez fichas do piloto. Ausência de um cadastro não demonstra inexistência de obra. A fonte não informou uma licença específica da API no material consultado; não atribuímos licença aos dados.</p><p>Para reproduzir as páginas, confira o <Link href="/metodologia">método e hash de entrada</Link>. <Link href="/levantamento">Veja o levantamento dos cinco recortes</Link>.</p></section>
</DiscoveryShell>}
