import * as maplibregl from 'maplibre-gl';
import workerUrl from 'maplibre-gl/dist/maplibre-gl-worker.mjs?worker&url';
import dataWorkerUrl from '../data-worker.js?worker&url';
import 'maplibre-gl/dist/maplibre-gl.css';
import './style.css';
import {expired} from './data.js';
import {matchesExactMunicipality,matchesProjectSearch} from './search.js';
import {investmentTotal,sortProjects} from './sort.js';
import {readListState,saveListState} from './list-state.js';
maplibregl.setWorkerUrl(workerUrl);

const icons={radar:'<circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="5"/><path d="M12 12 19 5M12 3v2M3 12h2M12 19v2M19 12h2"/><circle cx="12" cy="12" r="1"/>',map:'<path d="m3 5 6-2 6 2 6-2v16l-6 2-6-2-6 2zM9 3v16M15 5v16"/>',list:'<path d="M8 6h13M8 12h13M8 18h13M3 6h.01M3 12h.01M3 18h.01"/>',search:'<circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/>',arrow:'<path d="M5 12h14m-5-5 5 5-5 5"/>',pin:'<path d="M20 10c0 6-8 11-8 11S4 16 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/>',close:'<path d="m6 6 12 12M6 18 18 6"/>',external:'<path d="M14 3h7v7m0-7L10 14M10 3H3v18h18v-7"/>',layers:'<path d="m12 3 10 6-10 6L2 9Zm-9 11 9 5 9-5M3 18l9 5 9-5"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',info:'<circle cx="12" cy="12" r="9"/><path d="M12 11v6M12 7h.01"/>',target:'<circle cx="12" cy="12" r="6"/><path d="M12 2v4M12 18v4M2 12h4M18 12h4"/>',filter:'<path d="M3 6h18M6 12h12M10 18h4"/>',building:'<path d="M4 21V5h10v16M14 10h6v11M8 9h2M8 13h2M8 17h2M2 21h20"/>',check:'<path d="m5 12 4 4L19 6"/>',download:'<path d="M12 3v12m-5-5 5 5 5-5M4 17v4h16v-4"/>'};
const icon=(name)=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[name]??icons.building}</svg>`;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=s=>s?new Intl.DateTimeFormat('pt-BR',{timeZone:'UTC'}).format(new Date(s)):'Não informada';
const timestamp=s=>s?new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short',timeZone:'UTC'}).format(new Date(s))+' UTC':'Não informado';
const money=v=>typeof v==='number'?new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',minimumFractionDigits:2,maximumFractionDigits:2}).format(v):'Não informado';
const palette={'Em execução':'#557942','Concluída':'#468ba0','Cadastrada':'#9a916e','Paralisada':'#b06a43','Inacabada':'#b06a43','Cancelada':'#887f81'};
const pilotPaths={
 '128622.33-16':'/obras/128622.33-16/reforma-pavilhao-rocha-lima-fiocruz',
 '7207.33-55':'/obras/7207.33-55/redes-esgoto-aguas-pluviais-hospital-bonsucesso',
 '4902.35-23':'/obras/4902.35-23/restaurante-estudantil-campus-pirituba',
 '59693.35-95':'/obras/59693.35-95/reforma-hospital-ruminantes-usp',
 '45919.31-65':'/obras/45919.31-65/anexo-escola-enfermagem-ufmg',
 '92142.31-00':'/obras/92142.31-00/manutencao-casa-conde-santa-marinha',
 '45892.29-61':'/obras/45892.29-61/escola-de-musica-ufba-segunda-etapa',
 '60185.29-20':'/obras/60185.29-20/recuperacao-fachadas-fiocruz-bahia',
 '30125.26-63':'/obras/30125.26-63/prevencao-incendio-hospital-clinicas-pe',
 '41201.26-60':'/obras/41201.26-60/residenciais-aeronautica-recife',
};
let data=[],meta={},overview=null,map=null,ready=false,selected=null,searchQuery='',exactMunicipalityQuery='',statusFilter='Todas',stateFilter='',onlyExpired=false,onlyViewport=false,view='map',locationLabel='Brasil',detailTab='overview',marker=null,sortKey=null,sortDirection='asc';
let filtered=[];
let listStateReady=false;
function rememberList(){if(!listStateReady||view!=='list')return;try{saveListState(window.sessionStorage,{query:searchQuery,uf:stateFilter,status:statusFilter,expired:onlyExpired,sort:sortKey,direction:sortDirection});}catch{/* Session storage can be unavailable. */}}
const fullPage=new URLSearchParams(window.location.search).get('ficha')==='1';
const fullPath=id=>pilotPaths[id]||`/obras/${encodeURIComponent(id)}`;
if(fullPage)document.body.classList.add('full-detail-page');
document.querySelector('#app').innerHTML=`
 <header class="header"><a class="brand" href="/" aria-label="Radar de Obras, início"><span class="brand-mark">${icon('radar')}</span><span>radar<span class="brand-light"> de obras</span><small>INFRAESTRUTURA À VISTA</small></span></a>
 <nav class="main-nav" aria-label="Visualizações"><button class="nav-tab active" data-view="map">${icon('map')} Mapa</button><button class="nav-tab" data-view="list">${icon('list')} Lista de obras</button></nav>
 <div class="header-right"><button id="freshness" class="quiet-button"><span class="status-dot"></span><span>Fontes e cobertura</span>${icon('info')}</button><span class="prototype">PROTÓTIPO</span></div></header>
 <main class="workspace"><aside class="sidebar"><div class="explore-head"><div class="eyebrow"><span class="tiny-line"></span> EXPLORE O TERRITÓRIO</div><h1>O Brasil em<br/>construção<span>.</span></h1><p>Descubra as obras, acompanhe os prazos<br class="desktop"/> e entenda o que muda perto de você.</p></div>
 <form id="search-form" class="search-form" role="search"><label class="sr-only" for="query">Buscar obra, cidade, endereço ou CEP</label><div class="search-input">${icon('search')}<input id="query" placeholder="Obra, cidade, endereço ou CEP" autocomplete="off"/><button aria-label="Buscar" title="Buscar">${icon('arrow')}</button></div></form>
 <div id="search-results" class="search-results" aria-live="polite"></div>
 <div class="filter-line"><label for="uf">${icon('filter')} Filtrar</label><select id="uf" aria-label="Estado"><option value="">Todos os estados</option></select><button id="reset" class="text-button">Limpar</button></div>
 <div class="status-filters" aria-label="Situação da obra"><button class="active" data-status="Todas">Todas</button><button data-status="Em execução"><i style="--status:#557942"></i>Em execução</button><button data-status="Cadastrada"><i style="--status:#9a916e"></i>Cadastrada</button><button data-status="Paralisada"><i style="--status:#b06a43"></i>Paralisada</button><button data-status="Concluída"><i style="--status:#468ba0"></i>Concluída</button><button data-status="Inacabada">Inacabada</button><button data-status="Cancelada">Cancelada</button></div>
 <label class="expired-filter"><input type="checkbox" id="expired"/><span>Previsão de término vencida</span>${icon('clock')}</label>
 <div class="results-heading"><span><strong id="result-count">—</strong> projetos encontrados</span><span id="sample-label">NA AMOSTRA</span></div><div id="cards" class="cards"><div class="loading">Carregando os dados públicos…</div></div>
 <footer class="sidebar-footer">${icon('info')}<span>Amostra de cadastros oficiais.<br/>Ausência no mapa não significa ausência de obra.</span><button id="about-button" aria-label="Entender os dados">${icon('arrow')}</button></footer></aside>
 <section class="map-area" aria-label="Mapa de projetos"><div id="map"></div><div class="map-top"><div class="territory"><span class="eyebrow">TERRITÓRIO EM FOCO</span><strong id="territory-name">Brasil</strong><span id="territory-count">Explorando os dados disponíveis</span></div><button id="area-button" class="map-button" hidden>${icon('search')} Buscar nesta área</button></div>
 <div class="map-controls"><button id="map-home" aria-label="Ver Brasil" title="Ver Brasil">BR</button><button id="zoom-in" aria-label="Aumentar zoom">+</button><button id="zoom-out" aria-label="Diminuir zoom">−</button><span></span><button id="pitch" aria-label="Alternar vista inclinada" title="Vista inclinada do mapa">${icon('layers')}</button><button id="locate" aria-label="Minha localização" title="Minha localização">${icon('target')}</button></div>
 <div class="map-bottom"><div class="map-key"><span><i style="--status:#557942"></i>Em execução</span><span><i style="--status:#9a916e"></i>Cadastrada</span><span><i style="--status:#b06a43"></i>Parada / inacabada</span><span><i style="--status:#468ba0"></i>Concluída</span></div><button id="coverage" class="coverage">${icon('info')} Como ler este mapa</button></div><div class="map-watermark">RADAR / BRASIL <span>01</span></div></section>
 <section id="list-view" class="list-view" hidden><div class="list-heading"><div class="eyebrow">OS DADOS, LADO A LADO</div><h2>Obras em perspectiva.</h2><p>Compare situação, localização, investimento e prazo nos cadastros encontrados.</p><button id="download" class="outline-button">${icon('download')} Exportar seleção</button></div><div class="list-toolbar" aria-label="Busca e filtros da lista"><form id="list-search-form" class="list-search-form" role="search"><label class="sr-only" for="list-query">Buscar obra, município, endereço, CEP ou identificador</label><div class="list-search-input">${icon('search')}<input id="list-query" type="search" placeholder="Buscar obra, município, endereço, CEP ou ID" autocomplete="off"/><button type="submit" aria-label="Buscar na lista" title="Buscar na lista">Buscar</button></div></form><details class="list-filter-popover"><summary>${icon('filter')}<span>Filtros</span><span id="list-filter-count" class="list-filter-count" hidden></span></summary><div class="list-filter-panel"><label>Estado<select id="list-uf" aria-label="Estado na lista"><option value="">Todos os estados</option></select></label><label>Situação<select id="list-status" aria-label="Situação da obra na lista"><option value="Todas">Todas as situações</option><option value="Em execução">Em execução</option><option value="Cadastrada">Cadastrada</option><option value="Paralisada">Paralisada</option><option value="Concluída">Concluída</option><option value="Inacabada">Inacabada</option><option value="Cancelada">Cancelada</option></select></label><label class="list-expired-filter"><input type="checkbox" id="list-expired"/> Previsão de término vencida</label><button type="button" class="text-button" data-clear-filters>Limpar filtros</button></div></details><div id="list-filter-chips" class="list-filter-chips" aria-live="polite"></div></div><div class="table-wrap"><table><thead><tr><th data-sort-column="name"><button class="sort-button" data-sort="name">Projeto / responsável<span class="sort-mark" aria-hidden="true"></span></button></th><th data-sort-column="location"><button class="sort-button" data-sort="location">Localidade<span class="sort-mark" aria-hidden="true"></span></button></th><th data-sort-column="status"><button class="sort-button" data-sort="status">Situação informada<span class="sort-mark" aria-hidden="true"></span></button></th><th data-sort-column="investment"><button class="sort-button" data-sort="investment">Investimento previsto<span class="sort-mark" aria-hidden="true"></span></button></th><th data-sort-column="end"><button class="sort-button" data-sort="end">Previsão de término<span class="sort-mark" aria-hidden="true"></span></button></th><th data-sort-column="progress"><button class="sort-button" data-sort="progress">Andamento informado<span class="sort-mark" aria-hidden="true"></span></button></th><th>Consulta rápida</th></tr></thead><tbody id="table-body"></tbody></table></div></section>
 <aside id="detail" class="detail" aria-label="Detalhes do projeto" hidden></aside></main>
 <dialog id="about"><button class="dialog-close" aria-label="Fechar">${icon('close')}</button><div class="eyebrow">FONTES E COBERTURA</div><h2>O que este radar vê — e o que ainda falta.</h2><p id="coverage-copy">Os pontos indicam a localização cadastrada pelo órgão; não confirmam o canteiro ou o trecho exato da obra.</p><div id="source-times"></div><div id="coverage-breakdown" class="coverage-breakdown"></div><div class="about-note"><strong>Automático não significa tempo real.</strong><p id="freshness-copy">A fonte pode manter dados antigos mesmo quando uma consulta acaba de acontecer.</p></div><section class="source-roadmap"><h3>Fontes que podem ampliar o radar</h3><a href="https://www.gov.br/pncp/pt-br/acesso-a-informacao/dados-abertos" target="_blank" rel="noreferrer"><strong>PNCP</strong><span>Licitações e contratos da União, estados e municípios. Contrato não prova que a obra começou.</span>${icon('external')}</a><a href="https://www.gov.br/casacivil/pt-br/novopac/transparencia" target="_blank" rel="noreferrer"><strong>Novo PAC</strong><span>Empreendimentos, estágio, execução e investimento; parte pode repetir o Obrasgov.</span>${icon('external')}</a><a href="https://api-publica.transferegov.gestao.gov.br/" target="_blank" rel="noreferrer"><strong>Transferegov</strong><span>Transferências, convênios, emendas e pagamentos ligados a recursos federais.</span>${icon('external')}</a><a href="https://simec.mec.gov.br/painelObras/" target="_blank" rel="noreferrer"><strong>FNDE Obras 2.0</strong><span>Escolas, creches e quadras financiadas pelo FNDE, com acompanhamento próprio.</span>${icon('external')}</a><a href="https://www.gov.br/dnit/pt-br/acesso-a-informacao/dados-abertos/conjuntos-de-dados" target="_blank" rel="noreferrer"><strong>DNIT e fontes setoriais</strong><span>Dados mais profundos de rodovias; saúde também tem o SISMOB Cidadão.</span>${icon('external')}</a><div class="source-local"><strong>Estados e municípios</strong><span>Obras pagas apenas com recursos locais exigem conectores por portal. Não existe hoje uma API única e completa para todo o país.</span></div></section><p>Endereços pesquisados são enviados ao Nominatim / OpenStreetMap, ou à BrasilAPI para CEPs, somente após confirmar a busca. Eles não são adicionados ao cadastro de obras.</p><a href="https://api-publica.obrasgov.gestao.gov.br/obras/openapi.json" target="_blank" rel="noreferrer">Consultar documentação do Obrasgov ${icon('external')}</a></dialog>
 <div id="toast" role="status" aria-live="polite"></div>`;
document.querySelector('#list-filter-chips').insertAdjacentHTML('afterend','<div id="list-search-feedback" class="list-search-feedback" aria-live="polite"></div>');

function badge(p){return `<span class="badge" style="--status:${palette[p.status]??'#888'}"><i></i>${esc(p.status)}</span>`;}
function location(p){return [p.city,p.uf].filter(Boolean).join(' · ')||'Localidade não informada';}
function title(p){const n=p.name;if(n.length>8&&n===n.toUpperCase())return n.charAt(0)+n.slice(1).toLowerCase();return n;}
function showToast(text){const el=document.querySelector('#toast');el.textContent=text;el.classList.add('visible');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>el.classList.remove('visible'),5500);}
function getFiltered(){return data.filter(p=>(statusFilter==='Todas'||p.status===statusFilter)&&(!stateFilter||p.uf===stateFilter)&&(!onlyExpired||expired(p))&&(!exactMunicipalityQuery||matchesExactMunicipality(p,exactMunicipalityQuery))&&matchesProjectSearch(p,searchQuery)&&(!onlyViewport||(p.point&&map?.getBounds().contains(p.point))));}
function syncListControls(){
 const listQuery=document.querySelector('#list-query'),listUf=document.querySelector('#list-uf'),listStatus=document.querySelector('#list-status'),listExpired=document.querySelector('#list-expired');
 if(listQuery)listQuery.value=searchQuery;if(listUf)listUf.value=stateFilter;if(listStatus)listStatus.value=statusFilter;if(listExpired)listExpired.checked=onlyExpired;
 const filters=[statusFilter!=='Todas'&&['status',`Situação: ${statusFilter}`],stateFilter&&['state',`Estado: ${stateFilter}`],onlyExpired&&['expired','Término vencido'],onlyViewport&&['viewport','Área do mapa']].filter(Boolean);
 const count=document.querySelector('#list-filter-count');count.hidden=!filters.length;count.textContent=filters.length;
 document.querySelector('#list-filter-chips').innerHTML=filters.map(([name,label])=>`<button type="button" class="list-filter-chip" data-clear-filter="${name}" aria-label="Remover filtro ${esc(label)}">${esc(label)} ${icon('close')}</button>`).join('');
}
function setSearchFeedback(markup){document.querySelector('#search-results').innerHTML=markup;document.querySelector('#list-search-feedback').innerHTML=view==='list'?markup:'';}
function syncSortHeaders(){document.querySelectorAll('[data-sort-column]').forEach(header=>{const active=header.dataset.sortColumn===sortKey;header.setAttribute('aria-sort',active?(sortDirection==='asc'?'ascending':'descending'):'none');header.querySelector('.sort-mark').textContent=active?(sortDirection==='asc'?'↑':'↓'):'↕';});}
function aggregatePoints(projects){
 const cells=new Map();
 for(const project of projects){if(!project.point)continue;const [lon,lat]=project.point,key=`${Math.floor(lon*2)},${Math.floor(lat*2)}`;const cell=cells.get(key)??{lon:0,lat:0,count:0};cell.lon+=lon;cell.lat+=lat;cell.count++;cells.set(key,cell);}
 return [...cells.values()].map((cell,index)=>({type:'Feature',geometry:{type:'Point',coordinates:[cell.lon/cell.count,cell.lat/cell.count]},properties:{cell:index,count:cell.count,color:'#526b5a'}}));
}
function mapFeatures(projects){return projects.filter(project=>project.point).map(project=>({type:'Feature',geometry:{type:'Point',coordinates:project.point},properties:{id:project.id,count:1,color:palette[project.status]??'#888'}}));}
function updateMapSource(){
 if(!ready||view!=='map')return;
 const source=map.getSource('works');if(!source)return;
 const defaultFilters=statusFilter==='Todas'&&!stateFilter&&!onlyExpired&&!onlyViewport&&!searchQuery&&!exactMunicipalityQuery;
 let features;
 if(map.getZoom()<7){features=defaultFilters&&overview?overview.featureCollection.features:aggregatePoints(filtered);}
 else{const bounds=map.getBounds();features=mapFeatures(filtered.filter(project=>project.point&&bounds.contains(project.point)));}
 source.setData({type:'FeatureCollection',features});
}
function update(){
 filtered=getFiltered();document.querySelector('#result-count').textContent=filtered.length;
 document.querySelector('#territory-count').textContent=`${filtered.filter(p=>p.point).length} projetos localizados nesta seleção`;
 document.querySelector('#territory-name').textContent=locationLabel;
 document.querySelector('#cards').innerHTML=filtered.length?filtered.slice(0,70).map(p=>`<button class="project-card ${selected?.id===p.id?'is-selected':''}" data-project="${esc(p.id)}"><div class="card-top"><span>${esc(location(p))}</span>${icon('arrow')}</div><h3>${esc(title(p))}</h3><div class="card-bottom">${badge(p)}<span class="card-date">${expired(p)?'<span class="expired-dot"></span>':''}${date(p.end)}</span></div>${!p.point?'<div class="no-point">Sem coordenada utilizável</div>':''}</button>`).join('')+(filtered.length>70?`<p class="list-limit">70 de ${filtered.length.toLocaleString('pt-BR')} cartões. Abra a lista para comparar até 1.000 resultados ou refine a busca.</p>`:''):'<div class="empty"><span>◎</span><h3>Nenhum projeto nesta seleção.</h3><p>Podem existir obras não registradas nas fontes consultadas. Tente ampliar a área ou limpar os filtros.</p><button class="outline-button" id="empty-reset">Limpar filtros</button></div>';
 const visibleRows=view==='list'?sortProjects(filtered,sortKey,sortDirection).slice(0,1000):[];
 document.querySelector('#table-body').innerHTML=(visibleRows.map(p=>`<tr><td><a class="table-project" data-full-page href="${esc(fullPath(p.id))}" target="_top">${esc(title(p))}</a><small>${esc(p.organization??'Órgão não informado')}</small></td><td>${esc(location(p))}<small>${p.point?'Ponto cadastrado':'Sem coordenada utilizável'}</small></td><td>${badge(p)}</td><td class="investment-cell">${investmentTotal(p)!=null?`${money(investmentTotal(p))}<small>Previsto na fonte</small>`:'<span class="muted">Não informado</span>'}</td><td>${date(p.end)}${expired(p)?'<small class="warning-text">Previsão vencida · verificar</small>':''}</td><td>${p.execution?.percentual_execucao_fisica!=null?`${p.execution.percentual_execucao_fisica}%<small>Informado em ${date(p.execution.dt_atualizacao_execucao)}</small>`:'<span class="muted">Abra a ficha para consultar</span>'}</td><td><button class="outline-button" data-project="${esc(p.id)}" aria-label="Resumo de ${esc(title(p))}">Resumo</button></td></tr>`).join('')||'<tr><td colspan="7">Nenhum projeto nesta seleção. Experimente limpar os filtros.</td></tr>')+(filtered.length>1000?`<tr><td colspan="7" class="list-limit">Mostrando 1.000 de ${filtered.length.toLocaleString('pt-BR')} resultados. Refine os filtros; a exportação inclui toda a seleção.</td></tr>`:'');
 updateMapSource();
 syncListControls();syncSortHeaders();
 rememberList();
}
function reset(){searchQuery='';exactMunicipalityQuery='';statusFilter='Todas';stateFilter='';onlyExpired=false;onlyViewport=false;document.querySelector('#query').value='';document.querySelector('#uf').value='';document.querySelector('#expired').checked=false;document.querySelectorAll('[data-status]').forEach(b=>b.classList.toggle('active',b.dataset.status==='Todas'));document.querySelector('.sidebar').classList.remove('search-active');setSearchFeedback('');update();}
function showView(next){if(next==='list'&&selected)closeDetail();view=next;if(listStateReady){const url=new URL(window.location.href);url.searchParams.set('view',view);window.history.replaceState(window.history.state,'',url);}document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));document.querySelector('#list-view').hidden=view!=='list';document.querySelector('.map-area').hidden=view!=='map';document.querySelector('.workspace').classList.toggle('list-mode',view==='list');update();if(view==='map')requestAnimationFrame(()=>map?.resize());}
function focusBrazil(){reset();showView('map');closeDetail();locationLabel='Brasil';map?.fitBounds([[-74,-34],[-34,6]],{padding:innerWidth<760?25:80,pitch:0,bearing:0,duration:1300});update();}
function closeDetail(){if(fullPage)return;selected=null;document.querySelector('#detail').hidden=true;document.querySelector('.workspace').classList.remove('detail-open');marker?.remove();marker=null;update();}
function row(label,value){return `<div class="fact"><span>${label}</span><strong>${value}</strong></div>`;}
function renderDetail(loading=false){
 const p=selected;if(!p)return;const panel=document.querySelector('#detail');panel.hidden=false;document.querySelector('.workspace').classList.add('detail-open');
 const publicPath=fullPath(p.id);
 if(fullPage)document.title=title(p)+' | Radar de Obras';
 const executors=Array.isArray(p.executors)?p.executors:[];
 const investments=Array.isArray(p.investments)?p.investments:[];
 const commitments=Array.isArray(p.commitments)?p.commitments:[];
 const contracts=Array.isArray(p.contracts)?p.contracts:[];
 const history=Array.isArray(p.history)?p.history:[];
 let content='';
 if(detailTab==='overview'){
  const exec=p.execution;
  content=`<section class="detail-section"><div class="section-caption">LOCALIZAÇÃO ${icon('pin')}</div><p class="address">${esc(p.address||'Endereço não informado no cadastro.')}</p><p class="fine">${esc(location(p))}${p.cep?` · CEP ${esc(p.cep)}`:''}</p><div class="location-note">${p.point?'Ponto cadastrado · trecho exato não confirmado':'Sem coordenada utilizável'}<small>${esc(p.locationMethod)}</small></div>${p.point?`<a class="source-link" href="https://www.google.com/maps/search/?api=1&query=${encodeURIComponent([p.point[1],p.point[0]].join(','))}" target="_blank" rel="noreferrer">Abrir no Google Maps ${icon('external')}</a>`:''}</section>
  <section class="detail-section"><div class="section-caption">PRAZO E ANDAMENTO ${icon('clock')}</div><div class="date-grid">${row('Início previsto',date(p.start))}${row('Término previsto',date(p.end))}</div>${expired(p)?'<div class="warning-box">Previsão vencida no cadastro.<br/><small>A situação atual precisa de confirmação.</small></div>':''}${row('Situação informada',esc(p.status))}${exec?.percentual_execucao_fisica!=null?`<div class="progress-label"><span>Execução física informada</span><strong>${esc(exec.percentual_execucao_fisica)}%</strong></div><div class="progress-track"><i style="width:${Math.min(100,Math.max(0,Number(exec.percentual_execucao_fisica)))}%"></i></div><p class="fine">Atualização do andamento: ${date(exec.dt_atualizacao_execucao)}</p>${p.status==='Concluída'&&Number(exec.percentual_execucao_fisica)<100?'<div class="warning-box">A fonte informa conclusão e execução inferior a 100%. Dados divergentes.</div>':''}`:`<p class="missing">${p.executions?.length>1?`${p.executions.length} medições distintas; não há um percentual único consolidado.`:p.detailErrors?.includes('execucao-fisica')?'Consulta de execução indisponível.':p.detailsChecked?'Nenhum registro de execução física retornado.':'Execução física ainda não consultada.'}</p>`}${row('Início efetivo',date(p.actualStart))}${row('Conclusão efetiva',date(p.actualEnd))}</section>
  <section class="detail-section"><div class="section-caption">QUEM RESPONDE ${icon('building')}</div><p>${esc(p.organization||'Não informado')}</p><p class="fine">Organização responsável · CNPJ ${esc(p.organizationCnpj||'não informado')}</p>${executors.map(e=>`<p class="executor">${esc(e.organizacao_executor)}<small>Executor informado</small></p>`).join('')}</section>`;
 }else if(detailTab==='money'){
  content=`<section class="detail-section"><div class="section-caption">INVESTIMENTO PREVISTO</div>${investments.length?investments.map(i=>row(esc(i.desc_nome_fonte_recurso||'Fonte não informada'),money(i.vl_investimento_previsto))).join(''):'<p class="missing">Não informado.</p>'}<p class="fine">Previsão de investimento. Não equivale a pagamento.</p></section><section class="detail-section"><div class="section-caption">EMPENHOS ENCONTRADOS</div>${commitments.length?commitments.map(e=>`<div class="finance-record">${row('Empenho',money(e.valor_empenho))}${row('Liquidado',money(e.liquidado))}${row('Pago',money(e.pago))}<small>${esc(e.nr_empenho||'Número não informado')} · Emissão ${date(e.data_emissao)}</small></div>`).join(''):`<p class="missing">${p.detailErrors?.includes('empenho')?'Consulta indisponível.':p.detailsChecked?'Nenhum empenho retornado.':'Empenhos ainda não consultados.'}</p>`}<p class="fine">Os valores mantêm a natureza informada pela fonte. Não somamos investimento previsto e empenhos.</p></section><section class="detail-section"><div class="section-caption">CONTRATOS</div>${contracts.length?contracts.map(c=>`<div class="finance-record"><p>${esc(c.fornecedor_contrato||'Fornecedor não informado')}</p>${row('Valor global',money(c.valor_global_contrato))}${row('Vigência até',date(c.vigencia_fim_contrato))}</div>`).join(''):`<p class="missing">${p.detailErrors?.includes('contrato')?'Consulta indisponível.':p.detailsChecked?'Nenhum contrato retornado nesta ficha. Isso não prova que não exista contrato.':'Contratos ainda não consultados.'}</p>`}</section>`;
 }else{
  content=`<section class="detail-section"><div class="section-caption">ORIGEM DOS DADOS</div>${row('Cadastro',esc(p.sourceSystem||'Obrasgov'))}${row('ID do projeto',esc(p.id))}${row('Consulta da ficha',timestamp(p.collectedAt))}${row('Carga geral informada',esc(meta.sourceLoad||'Não informada'))}${p.endpointCollectedAt?Object.entries(p.endpointCollectedAt).map(([name,time])=>row(esc(name),timestamp(time))).join(''):''}<a class="source-link" href="${esc(p.sourceUrl)}" target="_blank" rel="noreferrer">Dados brutos da fonte (JSON) ${icon('external')}</a><p class="fine">Data da carga geral não é data de atualização desta obra.</p></section><section class="detail-section"><div class="section-caption">FOTOGRAFIAS E INTERDIÇÕES</div><p class="missing">Ainda não há fotografias verificadas nem avisos de interdição vinculados a esta ficha.</p><p class="fine">Imagens do mapa ou Street View não confirmam o estado atual da obra. Esta versão não usa imagens ilustrativas como evidência.</p></section><section class="detail-section"><div class="section-caption">HISTÓRICO DA FONTE</div>${history.length?history.map(h=>`<p>${esc(h.descricao_historico_situacao_investimento)} · ${date(h.data_historico_situacao_investimento)}</p><p class="fine">${esc(h.justificativa_cancelada_paralisada||'Justificativa não informada')}</p>`).join(''):`<p class="missing">${p.detailErrors?.includes('historico-situacao-cancelada-paralisada')?'Consulta de histórico indisponível.':p.detailsChecked?'Nenhum histórico de paralisação ou cancelamento retornado.':'Histórico ainda não consultado.'}</p>`}</section>`;
 }
 panel.innerHTML=`<div class="detail-toolbar"><span>${fullPage?'FICHA DO PROJETO':'RESUMO DO PROJETO'}</span>${fullPage?'<a href="/radar.html?view=list" target="_top">Voltar à lista</a>':`<button id="close-detail" aria-label="Fechar resumo">${icon('close')}</button>`}</div><div class="detail-header">${badge(p)}<${fullPage?'h1':'h2'}>${esc(title(p))}</${fullPage?'h1':'h2'}><p>${esc(location(p))} <span> / ${esc(p.id)}</span></p>${!fullPage?`<a class="detail-full-link" data-full-page href="${esc(publicPath)}" target="_top">Abrir página completa ${icon('arrow')}</a>`:''}</div><div class="detail-tabs"><button data-detail-tab="overview" class="${detailTab==='overview'?'active':''}">Visão geral</button><button data-detail-tab="money" class="${detailTab==='money'?'active':''}">Dinheiro</button><button data-detail-tab="source" class="${detailTab==='source'?'active':''}">Fontes</button></div><div class="detail-scroll">${loading?'<div class="refresh-note">Consultando os detalhes na fonte…</div>':''}${p.fallbackEndpoints?.length?`<div class="warning-box">Dados preservados de ${timestamp(p.seedFallbackCollectedAt)}: ${esc(p.fallbackEndpoints.join(', '))}. A atualização desses campos falhou.</div>`:''}${p.detailErrors?.length?`<div class="warning-box">Consulta parcial: ${esc(p.detailErrors.join(', '))}. Campos indisponíveis não significam ausência.</div>`:''}${p.truncatedEndpoints?.length?`<div class="warning-box">Consulta incompleta: ${esc(p.truncatedEndpoints.join(', '))}. Pode haver registros adicionais.</div>`:''}${content}</div><div class="detail-footer">${icon('clock')}<span>Consulta ${timestamp(p.collectedAt)}<br/><small>O órgão pode ter informado o andamento antes disso.</small></span></div>`;
}
async function openDetail(id){
 selected=data.find(p=>p.id===id);if(!selected)return;detailTab='overview';renderDetail(true);update();
 if(selected.point&&map){marker?.remove();const el=document.createElement('div');el.className='selected-marker';marker=new maplibregl.Marker({element:el}).setLngLat(selected.point).addTo(map);map.flyTo({center:selected.point,zoom:Math.max(map.getZoom(),12.5),offset:innerWidth>1100?[-190,0]:[0,-60],duration:1300});}
 try{const r=await fetch(`/api/detail?id=${encodeURIComponent(id)}`);const body=await r.json();if(!r.ok)throw Error(body.error);const index=data.findIndex(p=>p.id===id);data[index]=body;if(selected?.id===id){selected=body;renderDetail();}update();}catch(e){if(selected?.id===id){renderDetail();showToast(e.message);}}
}
async function search(q,{preserveFilters=false}={}){
 if(selected)closeDetail();searchQuery=q;exactMunicipalityQuery=data.some(p=>matchesExactMunicipality(p,q))?q:'';
 if(!preserveFilters){statusFilter='Todas';stateFilter='';onlyExpired=false;onlyViewport=false;document.querySelector('#uf').value='';document.querySelector('#expired').checked=false;document.querySelectorAll('[data-status]').forEach(b=>b.classList.toggle('active',b.dataset.status==='Todas'));}
 document.querySelector('#query').value=q;document.querySelector('.sidebar').classList.toggle('search-active',Boolean(q)&&view==='map');update();
 if(!q){setSearchFeedback('');return;}
 const localMatches=data.some(p=>matchesProjectSearch(p,q)&&(!exactMunicipalityQuery||matchesExactMunicipality(p,exactMunicipalityQuery)));
 if(localMatches){locationLabel=exactMunicipalityQuery?`Cidade: ${data.find(p=>matchesExactMunicipality(p,q))?.city??q}`:'Resultados da busca';update();if(view==='map'&&filtered.some(p=>p.point)&&map){const bounds=new maplibregl.LngLatBounds();filtered.filter(p=>p.point).forEach(p=>bounds.extend(p.point));map.fitBounds(bounds,{padding:100,maxZoom:13,duration:1200});}const status=`<div class="search-status"><span><strong>${filtered.length.toLocaleString('pt-BR')}</strong> projetos encontrados${exactMunicipalityQuery?` em ${esc(data.find(p=>matchesExactMunicipality(p,q))?.city??q)}`:''}${!filtered.length?' com os filtros atuais':''}</span>${view==='map'?'<button id="show-list" class="search-action">Ver lista</button><button id="geocode-anyway" class="search-action secondary">'+icon('pin')+' Localizar como endereço</button>':''}</div>`;setSearchFeedback(status);return;}
 await geocode(q);
}
async function geocode(q){
 setSearchFeedback('<div class="search-status" aria-live="polite"><span>Consultando endereço…</span></div>');
 try{const r=await fetch(`/api/geocode?q=${encodeURIComponent(q)}`);const rows=await r.json();if(!r.ok)throw Error(rows.error);setSearchFeedback(rows.length?`<div class="search-status"><span>Busca ativa</span>${rows.map((x,i)=>`<button data-geocode="${i}" class="search-action secondary">${icon('pin')} ${esc(x.label)}</button>`).join('')}</div>`:'<div class="search-status"><span>Busca ativa</span></div>');geocode.results=rows;}catch{setSearchFeedback('<div class="search-status"><span>Busca ativa</span></div>');}
}
function initMap(){
 try{
  map=new maplibregl.Map({container:'map',center:[-51,-14.5],zoom:innerWidth<760?2:3.65,minZoom:1,maxZoom:18,style:'https://tiles.openfreemap.org/styles/positron',attributionControl:{compact:false}});
  map.addControl(new maplibregl.ScaleControl({maxWidth:110,unit:'metric'}),'bottom-left');
  map.on('load',()=>{
   map.addLayer({id:'context-buildings',type:'fill-extrusion',source:'openmaptiles','source-layer':'building',minzoom:14,layout:{visibility:'none'},paint:{'fill-extrusion-color':'#a9b5a0','fill-extrusion-height':['coalesce',['get','render_height'],0],'fill-extrusion-base':['coalesce',['get','render_min_height'],0],'fill-extrusion-opacity':.8}});
   map.addSource('works',{type:'geojson',data:{type:'FeatureCollection',features:[]},cluster:true,clusterMaxZoom:10,clusterRadius:38,clusterProperties:{project_count:['+',['get','count']]}});
   map.addLayer({id:'clusters-glow',type:'circle',source:'works',filter:['has','point_count'],paint:{'circle-color':'#38503a','circle-radius':['step',['get','project_count'],23,10,29,30,35],'circle-opacity':.08}});
   map.addLayer({id:'clusters',type:'circle',source:'works',filter:['has','point_count'],paint:{'circle-color':'#334b35','circle-radius':['step',['get','project_count'],15,10,20,30,25],'circle-stroke-width':2,'circle-stroke-color':'#f4f4e9'}});
   map.addLayer({id:'counts',type:'symbol',source:'works',filter:['has','point_count'],layout:{'text-field':['to-string',['get','project_count']],'text-font':['Noto Sans Regular'],'text-size':12},paint:{'text-color':'#fff'}});
   map.addLayer({id:'point-glow',type:'circle',source:'works',filter:['!', ['has','point_count']],paint:{'circle-color':['get','color'],'circle-radius':13,'circle-opacity':.16}});
   map.addLayer({id:'points',type:'circle',source:'works',filter:['!', ['has','point_count']],paint:{'circle-color':['get','color'],'circle-radius':['case',['has','cell'],['step',['get','count'],6,10,9,100,12],6],'circle-stroke-width':2,'circle-stroke-color':'#fff'}});
   map.addLayer({id:'overview-counts',type:'symbol',source:'works',filter:['has','cell'],layout:{'text-field':['to-string',['get','count']],'text-font':['Noto Sans Regular'],'text-size':10},paint:{'text-color':'#fff'}});
   map.on('click','points',e=>{const feature=e.features[0];if(feature.properties.id)void openDetail(feature.properties.id);else map.easeTo({center:feature.geometry.coordinates,zoom:Math.max(7,map.getZoom()+2),duration:650});});
   map.on('click','clusters',async e=>{const f=e.features[0];const zoom=await map.getSource('works').getClusterExpansionZoom(f.properties.cluster_id);map.easeTo({center:f.geometry.coordinates,zoom,duration:650});});
   for(const layer of ['points','clusters']){map.on('mouseenter',layer,()=>map.getCanvas().style.cursor='pointer');map.on('mouseleave',layer,()=>map.getCanvas().style.cursor='');}
   ready=true;if(data.length)update();else updateMapSource();
  });
  map.on('moveend',()=>{document.querySelector('#area-button').hidden=false;if(onlyViewport)update();else updateMapSource();});
  let tileError=false;map.on('error',()=>{if(!tileError){tileError=true;showToast('Parte do mapa pode estar indisponível. A lista de projetos continua acessível.');}});
 }catch{document.querySelector('#map').innerHTML='<div class="map-fallback"><h2>O mapa precisa de WebGL.</h2><p>Use a Lista de obras para consultar todos os projetos neste navegador.</p></div>';showView('list');}
}
function showAbout(){
 if(!data.length){document.querySelector('#coverage-copy').textContent='A visão nacional já representa a carga oficial; os registros individuais ainda estão carregando.';document.querySelector('#source-times').textContent=`Carga informada: ${overview?.sourceLoad??'consultando fonte'}`;document.querySelector('#coverage-breakdown').textContent='Aguarde o carregamento dos detalhes para conferir a distribuição por UF.';document.querySelector('#about').showModal();return;}
 document.querySelector('#coverage-copy').textContent=meta.full?'Esta carga contém todos os cadastros retornados pelo endpoint de projetos do Obrasgov. Isso não significa todas as obras existentes no Brasil. Os pontos não confirmam o canteiro ou trecho exato.':'Esta versão usa uma amostra de registros do Obrasgov. Os pontos não confirmam o canteiro ou trecho exato.';
 document.querySelector('#freshness-copy').textContent=meta.full?'A base nacional é um snapshot validado. Cada ficha consulta os detalhes na API ao ser aberta. Uma coleta recente não garante que o órgão tenha atualizado aquela obra.':'O processo local consulta a amostra a cada 6 horas enquanto estiver ativo. Cada ficha tenta atualizar os detalhes. A fonte pode manter dados antigos.';
 document.querySelector('#source-times').innerHTML=`${row('Carga informada pelo Obrasgov',esc(meta.sourceLoad||'Não informada'))}${row('Nossa coleta',timestamp(meta.collectedAt))}${row('Cadastros carregados',data.length.toLocaleString('pt-BR'))}<p class="fine">${esc(meta.scope||'')}</p>${meta.lastError?`<div class="warning-box">Última atualização falhou. Exibindo versão preservada: ${esc(meta.lastError)}</div>`:''}`;
 const byUf=data.reduce((counts,p)=>(p.uf&&(counts[p.uf]=(counts[p.uf]||0)+1),counts),{});const ranking=Object.entries(byUf).sort((a,b)=>b[1]-a[1]);const rj=byUf.RJ||0;const rjRank=ranking.findIndex(([uf])=>uf==='RJ')+1;const pct=value=>(100*value/data.length).toLocaleString('pt-BR',{maximumFractionDigits:1});
 document.querySelector('#coverage-breakdown').innerHTML=`<h3>Distribuição desta carga</h3><div class="coverage-numbers">${ranking.slice(0,3).map(([uf,total])=>`<span><strong>${esc(uf)}</strong>${total.toLocaleString('pt-BR')} <small>${pct(total)}%</small></span>`).join('')}</div><p><strong>Rio de Janeiro:</strong> ${rj.toLocaleString('pt-BR')} registros · ${pct(rj)}% · ${rjRank}º entre as UFs.</p><p class="fine">O Rio não concentra a maioria. Muitos cadastros compartilham coordenadas municipais, então um único agrupamento no mapa pode parecer desproporcional.</p><div class="scope-current"><strong>Cobertura atual: Obrasgov</strong><span>Obrigatória para infraestrutura custeada pelo orçamento federal. Estados e municípios podem cadastrar obras de recursos próprios por adesão, mas isso é facultativo.</span></div>`;document.querySelector('#about').showModal();
}
document.addEventListener('click',e=>{
 if(e.target.closest('[data-full-page]'))return;
 const project=e.target.closest('[data-project]');if(project){void openDetail(project.dataset.project);return;}
 const tab=e.target.closest('[data-view]');if(tab){showView(tab.dataset.view);return;}
 const sort=e.target.closest('[data-sort]');if(sort){const next=sort.dataset.sort;if(sortKey===next)sortDirection=sortDirection==='asc'?'desc':'asc';else{sortKey=next;sortDirection=['investment','progress'].includes(next)?'desc':'asc';}update();return;}
 const status=e.target.closest('[data-status]');if(status){statusFilter=status.dataset.status;document.querySelectorAll('[data-status]').forEach(b=>b.classList.toggle('active',b===status));update();return;}
 const clearFilter=e.target.closest('[data-clear-filter]');if(clearFilter){const name=clearFilter.dataset.clearFilter;if(name==='status')statusFilter='Todas';if(name==='state')stateFilter='';if(name==='expired')onlyExpired=false;if(name==='viewport')onlyViewport=false;document.querySelector('#uf').value=stateFilter;document.querySelector('#expired').checked=onlyExpired;document.querySelectorAll('[data-status]').forEach(b=>b.classList.toggle('active',b.dataset.status===statusFilter));update();return;}
 if(e.target.closest('[data-clear-filters]')){statusFilter='Todas';stateFilter='';onlyExpired=false;onlyViewport=false;document.querySelector('#uf').value='';document.querySelector('#expired').checked=false;document.querySelectorAll('[data-status]').forEach(b=>b.classList.toggle('active',b.dataset.status==='Todas'));update();return;}
 const dt=e.target.closest('[data-detail-tab]');if(dt){detailTab=dt.dataset.detailTab;renderDetail();return;}
 const geo=e.target.closest('[data-geocode]');if(geo){const r=geocode.results[Number(geo.dataset.geocode)];searchQuery='';exactMunicipalityQuery='';onlyViewport=true;locationLabel=r.label.split(',').slice(0,2).join(',');document.querySelector('.sidebar').classList.remove('search-active');showView('map');map?.flyTo({center:r.point,zoom:14,duration:1400});document.querySelector('#search-results').innerHTML='';showToast(r.precision);update();return;}
 if(e.target.closest('#close-detail'))closeDetail();
 if(e.target.closest('#reset,#empty-reset'))reset();
 if(e.target.closest('#map-home'))focusBrazil();
 if(e.target.closest('#zoom-in'))map?.zoomIn();if(e.target.closest('#zoom-out'))map?.zoomOut();
 if(e.target.closest('#pitch')&&ready){const on=map.getPitch()===0;map.setLayoutProperty('context-buildings','visibility',on?'visible':'none');map.easeTo({center:selected?.point??map.getCenter(),zoom:on?Math.max(map.getZoom(),15.5):map.getZoom(),pitch:on?55:0,bearing:on?-20:0,duration:1100});showToast(on?'Edifícios de contexto do OpenStreetMap. Alturas podem ser estimadas; não são modelos das obras.':'Vista 2D.');}
 if(e.target.closest('#area-button')){onlyViewport=true;searchQuery='';exactMunicipalityQuery='';document.querySelector('#query').value='';locationLabel='Área selecionada';update();}
 if(e.target.closest('#freshness,#about-button,#coverage'))showAbout();
 if(e.target.closest('.dialog-close'))document.querySelector('#about').close();
 if(e.target.closest('#geocode-anyway'))void geocode(document.querySelector('#query').value.trim());
 if(e.target.closest('#show-list')){showView('list');return;}
 if(e.target.closest('#locate')){if(!navigator.geolocation){showToast('Localização indisponível neste navegador.');return;}navigator.geolocation.getCurrentPosition(p=>{onlyViewport=true;searchQuery='';exactMunicipalityQuery='';locationLabel='Perto de você';map?.flyTo({center:[p.coords.longitude,p.coords.latitude],zoom:13});update();},()=>showToast('Não foi possível acessar sua localização. Você pode buscar por endereço.'));}
 if(e.target.closest('#download')){
  const cells=v=>`"${String(v??'').replace(/^([=+@-])/,'\'$1').replaceAll('"','""')}"`;
  const csv=[['ID','Projeto','UF','Municipio','Situacao','Investimento previsto','Fim previsto','Fonte'],...sortProjects(filtered,sortKey,sortDirection).map(p=>[p.id,p.name,p.uf,p.city,p.status,investmentTotal(p),p.end,p.sourceUrl])].map(r=>r.map(cells).join(';')).join('\r\n');const url=URL.createObjectURL(new Blob(['\uFEFF'+csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='radar-de-obras-selecao.csv';a.click();URL.revokeObjectURL(url);
 }
});
document.querySelector('#search-form').addEventListener('submit',e=>{e.preventDefault();void search(document.querySelector('#query').value.trim());});
document.querySelector('#list-search-form').addEventListener('submit',e=>{e.preventDefault();void search(document.querySelector('#list-query').value.trim(),{preserveFilters:true});});
document.querySelector('#uf').addEventListener('change',e=>{stateFilter=e.target.value;onlyViewport=false;update();});
document.querySelector('#expired').addEventListener('change',e=>{onlyExpired=e.target.checked;update();});
document.querySelector('#list-uf').addEventListener('change',e=>{stateFilter=e.target.value;onlyViewport=false;document.querySelector('#uf').value=stateFilter;update();});
document.querySelector('#list-status').addEventListener('change',e=>{statusFilter=e.target.value;document.querySelectorAll('[data-status]').forEach(b=>b.classList.toggle('active',b.dataset.status===statusFilter));update();});
document.querySelector('#list-expired').addEventListener('change',e=>{onlyExpired=e.target.checked;document.querySelector('#expired').checked=onlyExpired;update();});
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeDetail();});
async function loadOverview(){
 try{const response=await fetch('/data/map-overview.json');if(!response.ok)throw Error('Visão nacional indisponível');const body=await response.json();if(!body.featureCollection?.features||!Number.isInteger(body.total))throw Error('Visão nacional inválida');overview=body;
  if(!data.length){document.querySelector('#result-count').textContent=body.total;document.querySelector('#territory-count').textContent=`${body.withPoint} projetos localizados nesta seleção`;document.querySelector('#sample-label').textContent='COBERTURA OBRASGOV';}
  updateMapSource();
 }catch(error){showToast(`Visão nacional indisponível: ${error.message}`);}
}
async function readProjects(){
 if(typeof Worker!=='undefined'){
  try{return await new Promise((resolve,reject)=>{const worker=new Worker(dataWorkerUrl);const timer=setTimeout(()=>{worker.terminate();reject(Error('Tempo de carga esgotado'));},90000);worker.onmessage=event=>{clearTimeout(timer);worker.terminate();if(event.data?.error)reject(Error(event.data.error));else resolve(event.data);};worker.onerror=event=>{clearTimeout(timer);worker.terminate();reject(Error(event.message||'Worker indisponível'));};worker.postMessage('load');});}
  catch(error){console.warn('Worker de dados indisponível; tentando leitura direta.',error);}
 }
 const manifestResponse=await fetch('/data/projects-manifest.json');if(manifestResponse.ok){const manifest=await manifestResponse.json();const chunks=await Promise.all(manifest.files.map(async file=>{const response=await fetch(file.url);if(!response.ok)throw Error(`Falha no bloco ${file.url}`);return response.json();}));return {meta:manifest.meta,projects:chunks.flat()};}
 const response=await fetch('/api/projects');if(!response.ok)throw Error('Falha na leitura dos dados');return response.json();
}
async function load(){try{
 if(data.length){const response=await fetch('/data/projects-manifest.json');if(response.ok){const manifest=await response.json();if(manifest.meta.sourceLoad===meta.sourceLoad)return;}}
 const body=await readProjects();if(!Array.isArray(body.projects)||body.projects.length!==body.meta.sourceTotal)throw Error('Contagem dos dados não confere com o manifesto');
 data=body.projects;meta=body.meta;
 const ufOptions='<option value="">Todos os estados</option>'+[...new Set(data.map(p=>p.uf).filter(Boolean))].sort((a,b)=>a.localeCompare(b)).map(uf=>`<option>${esc(uf)}</option>`).join('');document.querySelector('#uf').innerHTML=ufOptions;document.querySelector('#list-uf').innerHTML=ufOptions;document.querySelector('#uf').value=stateFilter;document.querySelector('#list-uf').value=stateFilter;document.querySelector('#sample-label').textContent=meta.full?'COBERTURA OBRASGOV':'NA AMOSTRA';document.querySelector('#freshness span:nth-child(2)').textContent='Fontes e cobertura';
 document.querySelectorAll('[data-requires-data]').forEach(element=>element.disabled=false);
 if(overview?.sourceLoad!==meta.sourceLoad)await loadOverview();
 update();
 }catch(error){document.querySelector('#cards').innerHTML=`<div class="empty"><h3>Dados indisponíveis.</h3><p>${esc(error.message)}. Recarregue a página.</p></div>`;}}
document.querySelectorAll('[data-view="list"],[data-status],#uf,#query,#search-form button,#expired,#reset').forEach(element=>{element.disabled=true;element.dataset.requiresData='';});
const deepId=new URLSearchParams(window.location.search).get('obra');
if(fullPage){
 const panel=document.querySelector('#detail');panel.hidden=false;panel.innerHTML='<p class="loading" role="status">Carregando a ficha…</p>';
 try{if(!deepId)throw Error('Identificador não informado.');const response=await fetch(`/api/detail?id=${encodeURIComponent(deepId)}`);if(!response.ok)throw Error('Não foi possível carregar esta obra.');selected=await response.json();renderDetail();}
 catch(error){panel.innerHTML=`<div class="detail-header"><h1>Ficha indisponível</h1><p>${esc(error.message)}</p><a class="source-link" href="/radar.html?view=list" target="_top">Voltar à lista de obras</a><button class="outline-button" id="retry-detail">Tentar novamente</button></div>`;document.querySelector('#retry-detail').addEventListener('click',()=>window.location.reload());}
}else{
 initMap();await loadOverview();await load();
 if(new URLSearchParams(window.location.search).get('view')==='list'){
  let saved=null;try{saved=readListState(window.sessionStorage);}catch{/* Public browsing works without storage. */}
  if(saved&&!deepId){searchQuery=saved.query;stateFilter=data.some(p=>p.uf===saved.uf)?saved.uf:'';statusFilter=saved.status;onlyExpired=saved.expired;sortKey=saved.sort;sortDirection=saved.direction;exactMunicipalityQuery=data.some(p=>matchesExactMunicipality(p,searchQuery))?searchQuery:'';document.querySelector('#query').value=searchQuery;document.querySelector('#uf').value=stateFilter;document.querySelector('#expired').checked=onlyExpired;document.querySelectorAll('[data-status]').forEach(b=>b.classList.toggle('active',b.dataset.status===statusFilter));}
  showView('list');
 }
 listStateReady=true;
 if(deepId&&data.some(project=>project.id===deepId))void openDetail(deepId);
 setInterval(load,5*60*1000);
}
let resizeTimer;window.addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>{map?.resize();if(locationLabel==='Brasil'&&!selected)map?.fitBounds([[-74,-34],[-34,6]],{padding:innerWidth<760?25:80,pitch:0,bearing:0,duration:0});},180);});

