import Link from 'next/link';
import { DiscoveryShell, PageSchema } from '@/components/discovery';
import {pageMetadata} from '@/lib/metadata';
export const metadata=pageMetadata('/guia-de-interpretacao','Como interpretar um cadastro de obra','Entenda situação, previsões, investimento e coordenadas no Radar de Obras sem tirar conclusões que os dados não sustentam.');
export default function Guide(){return <DiscoveryShell crumbs={[{name:'Início',path:'/'},{name:'Como interpretar',path:'/guia-de-interpretacao'}]}>
  <PageSchema path="/guia-de-interpretacao" name="Como interpretar um cadastro de obra" description="Guia de leitura de situação, datas, valor e localização nos registros Obrasgov." />
  <div className="eyebrow">Guia rápido</div><h1>Como interpretar um cadastro de obra</h1><p className="lead">Uma ficha resume dados informados por órgãos na plataforma Obrasgov. Ela ajuda a encontrar a fonte e formular perguntas; não substitui a conferência documental ou em campo.</p>
  <div className="guide-grid"><section><h2>“Em execução” é a situação cadastrada</h2><p>O rótulo pode estar desatualizado. Compare a data da coleta e abra a fonte para conferir alterações recentes.</p></section><section><h2>Previsão vencida não comprova atraso</h2><p>A data pode ter sido revista ou a situação pode não ter sido atualizada. Procure documentos e informações do órgão responsável antes de concluir.</p></section><section><h2>Valor previsto não é gasto</h2><p>O campo de investimento previsto descreve planejamento. Para pagamentos ou execução financeira, são necessárias fontes próprias e definições compatíveis.</p></section><section><h2>O ponto não precisa ser o canteiro</h2><p>Coordenadas e municípios podem representar uma referência administrativa. Projetos regionais podem aparecer vinculados a uma cidade.</p></section><section><h2>Ausência no mapa não é inexistência</h2><p>O Radar cobre a resposta do cadastro consultado em uma coleta específica. Outros sistemas e entes podem registrar projetos fora desse recorte.</p></section><section><h2>Datas são fotografias, não histórico</h2><p>Sem snapshots anteriores validados, não afirmamos quando um campo mudou. Cada ficha informa a data da fotografia e da consulta complementar.</p></section></div>
  <p className="context-note"><Link href="/obras">Veja as dez fichas do piloto</Link> · <Link href="/metodologia">Leia a metodologia completa</Link>.</p>
</DiscoveryShell>}
